nelmio_api_doc:
    documentation:
        info:
            title: Docker Workshop API
            description: Demo API for Podlodka PHP Crew 8
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api
