include:
  - path: compose/proxy.yml
  - path: compose/database.yml
  - path: compose/cache.yml
  - path: compose/search.yml
  - path: compose/mail.yml
  - path: compose/storage.yml
  - path: compose/app.yml
  - path: compose/tunnel.yml
  - path: compose/debug.yml
  - path: compose/test.yml

networks:
  workshop:
    name: workshop
