; Base PHP configuration
expose_php = 0
date.timezone = UTC
memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 64M

; OPcache
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1

; Realpath cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600
