services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://app:8080
    networks:
      - workshop
    depends_on:
      - app
    profiles:
      - tunnel
